[theme]
# Primary accent color for interactive elements.
primaryColor = "gold"

# Background color for the main content area.
backgroundColor = "#001731"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#002349"

# Color used for almost all text.
textColor = "#eeeeee"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
font = "sans serif"

[client]
toolbarMode = "minimal"